In [3]:
import torch
import numpy as np

In [5]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [7]:
x_data

tensor([[1, 2],
        [3, 4]])

In [9]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)

In [13]:
x_ones=torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [15]:
x_rand=torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.0122, 0.9003],
        [0.3011, 0.2831]])

In [21]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.9559, 0.6124, 0.4229],
        [0.4837, 0.3145, 0.6782]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [23]:
tensor=torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [25]:
if torch.cuda.is_available():
    tensor=tensor.to("cuda")

In [29]:
tensor=torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"first column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [33]:
t1=torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [43]:
y1=tensor@tensor.T
y2=tensor.matmul(tensor.T)
y3=torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1=tensor*tensor
z2=tensor.mul(tensor)
z3=torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [45]:
agg=tensor.sum()
agg_item=agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [47]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [49]:
t=torch.ones(5)
print(t)
n=t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [51]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [53]:
n=np.ones(5)
t=torch.from_numpy(n)


In [55]:
np.add(n,1,out=n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
